// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagon.Infrastructure.Data;

#nullable disable

namespace WhiteLagon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251006103028_aminitytodb")]
    partial class aminitytodb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagon.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amenity 1",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Amenity 2",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amenity 3",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amenity 4",
                            VillaId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amenity 5",
                            VillaId = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Amenity 6",
                            VillaId = 2
                        });
                });

            modelBuilder.Entity("WhiteLagon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupency")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_At = new DateTime(2025, 10, 6, 10, 30, 28, 533, DateTimeKind.Utc).AddTicks(592),
                            Description = "Description for Villa 1",
                            ImageUrl = "https://example.com/villa1.jpg",
                            Name = "Villa 1",
                            Occupency = 2,
                            Price = 1000,
                            Sqft = 500,
                            Updated_At = new DateTime(2025, 10, 6, 10, 30, 28, 533, DateTimeKind.Utc).AddTicks(593)
                        },
                        new
                        {
                            Id = 2,
                            Created_At = new DateTime(2025, 10, 6, 10, 30, 28, 533, DateTimeKind.Utc).AddTicks(596),
                            Description = "Description for Villa 2",
                            ImageUrl = "https://example.com/villa2.jpg",
                            Name = "Villa 2",
                            Occupency = 4,
                            Price = 1200,
                            Sqft = 700,
                            Updated_At = new DateTime(2025, 10, 6, 10, 30, 28, 533, DateTimeKind.Utc).AddTicks(596)
                        },
                        new
                        {
                            Id = 3,
                            Created_At = new DateTime(2025, 10, 6, 10, 30, 28, 533, DateTimeKind.Utc).AddTicks(598),
                            Description = "Description for Villa 3",
                            ImageUrl = "https://example.com/villa3.jpg",
                            Name = "Villa 3",
                            Occupency = 6,
                            Price = 2000,
                            Sqft = 900,
                            Updated_At = new DateTime(2025, 10, 6, 10, 30, 28, 533, DateTimeKind.Utc).AddTicks(598)
                        },
                        new
                        {
                            Id = 4,
                            Created_At = new DateTime(2025, 10, 6, 10, 30, 28, 533, DateTimeKind.Utc).AddTicks(599),
                            Description = "Description for Villa 4",
                            ImageUrl = "https://example.com/villa4.jpg",
                            Name = "Villa 4",
                            Occupency = 8,
                            Price = 900,
                            Sqft = 1100,
                            Updated_At = new DateTime(2025, 10, 6, 10, 30, 28, 533, DateTimeKind.Utc).AddTicks(600)
                        });
                });

            modelBuilder.Entity("WhiteLagon.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 104,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 105,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 303,
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("WhiteLagon.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("WhiteLagon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("WhiteLagon.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WhiteLagon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
